name: Simple CI
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Codecov
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
